architecture_task:
  description: >
    Analyze research paper and create technical implementation plan.
    Identify required components and create file structure blueprint.
  expected_output: >
    Markdown document outlining implementation plan and file structure
  agent: code_architect

development_task:
  description: >
    Convert architecture plan into working Python code.
    Implement components with proper error handling and PEP8 compliance.
  expected_output: >
    Python code files wrapped in markdown code blocks with filenames.
    Format: ```filename.py\ncode\n```
  agent: developer

review_task:
  description: >
    Perform static analysis on generated code.
    Check for syntax errors and potential issues.
    Verify PEP8 compliance and proper error handling.
  expected_output: >
    List of found issues or 'APPROVED' if code is valid
  agent: code_review

qa_task:
  description: >
    Validate final code implementation against original requirements.
    Ensure all components from architecture plan are implemented.
  expected_output: >
    Validation report with PASS/FAIL status
  agent: qa_engineer